function sim_path_f = sde_Lamperti_FE(sim_path_i,alpha,theta_0,Theta_t,dt,P,P_dot) % 02/02/2020 18:28

    sim_path_f = sim_path_i + dt * ((alpha*theta_0-Theta_t)*sin(sqrt(2*alpha*theta_0)*sim_path_i) - ...
                Theta_t*(1-2*P)+2*P_dot) / (sqrt(2*alpha*theta_0)*cos(sqrt(2*alpha*theta_0)*sim_path_i)) + ...
                sqrt(dt)*randn(1);
            
%     sim_path_f = sim_path_i + dt * ((alpha*theta_0-Theta_t)*cos(sqrt(2*alpha*theta_0)*sim_path_i) - ...
%         Theta_t*(1-2*P)+2*P_dot) / (sqrt(alpha*theta_0)*(1-cos(2*sqrt(2*alpha*theta_0)*sim_path_i))) + ...
%         sqrt(dt)*randn(1);
    
end