Description of batch_with_theta
Home > . > batch_with_theta.m
batch_with_theta
PURPOSE
SYNOPSIS
function [batch_theta] = batch_with_theta(batch, alpha, theta_0) % 09/02/2020 18:51
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
theta_t
This function is called by:
initial_time
likelihood_optimization 10/02/2020 11:20
likelihood_optimization_MODEL1 19/04/2020 22:08
likelihood_optimization_MODEL1_gamma 19/04/2020 22:08
likelihood_optimization_all 10/02/2020 11:20
plotLamperti_V2
plotLogLikelihood
plotLogLikelihood_MODEL1
testingFile
DOWNLOAD
batch_with_theta.m
SOURCE CODE
function [batch_theta] = batch_with_theta(batch, alpha, theta_0) % 09/02/2020 18:51
    batch(4,1)   = theta_t(theta_0, alpha, batch(1,1), batch(2,1));
    batch(4,end) = theta_t(theta_0, alpha, batch(1,end), batch(2,end));
    for i = 2:2:length(batch(1,:))-1
        batch(4,i:i+1) = theta_t(theta_0, alpha, batch(1,i), batch(2,i));
    end
    batch_theta = batch;
end