Description of ciplot
Home > . > ciplot.m
ciplot
PURPOSE
ciplot(lower,upper)
SYNOPSIS
function ciplot(lower,upper,x,colour,alpha);
DESCRIPTION
 ciplot(lower,upper)
 ciplot(lower,upper,x)
 ciplot(lower,upper,x,colour)
 Plots a shaded region on a graph between specified lower and upper confidence intervals (L and U).
 l and u must be vectors of the same length.
 Uses the 'fill' function, not 'area'. Therefore multiple shaded plots
 can be overlayed without a problem. Make them transparent for total visibility.
 x data can be specified, otherwise plots against index values.
 colour can be specified (eg 'k'). Defaults to blue.
CROSS-REFERENCE INFORMATION
This function calls:
set TEMPLATE/SET Edit data stored in a Template object
This function is called by:
path_simulator_IG
path_simulator_Lamperti
path_simulator_OPT
path_simulator_OPT_forSuppMat Supplementary Material for the Wind-Power Paper.
path_simulator_OPT_model_1
DOWNLOAD
ciplot.m
SOURCE CODE
function ciplot(lower,upper,x,colour,alpha);
% ciplot(lower,upper)
% ciplot(lower,upper,x)
% ciplot(lower,upper,x,colour)
%
% Plots a shaded region on a graph between specified lower and upper confidence intervals (L and U).
% l and u must be vectors of the same length.
% Uses the 'fill' function, not 'area'. Therefore multiple shaded plots
% can be overlayed without a problem. Make them transparent for total visibility.
% x data can be specified, otherwise plots against index values.
% colour can be specified (eg 'k'). Defaults to blue.
% Raymond Reynolds 24/11/06
if length(lower)~=length(upper)
    error('lower and upper vectors must be same length')
end
if nargin<5
    alpha=1;
end
if nargin<4
    colour='b';
end
if nargin<3
    x=1:length(lower);
end
% convert to row vectors so fliplr can work
if find(size(x)==(max(size(x))))<2
x=x'; end
if find(size(lower)==(max(size(lower))))<2
lower=lower'; end
if find(size(upper)==(max(size(upper))))<2
upper=upper'; end
f = fill([x fliplr(x)],[upper fliplr(lower)],'r');
set(f,'FaceAlpha',alpha);
set(f,'FaceColor',colour);