Description of initial_guess
Home > . > initial_guess.m
initial_guess
PURPOSE
09/02/2020 09:30
SYNOPSIS
function [est] = initial_guess(real_prod, M, N, dt)
DESCRIPTION
 09/02/2020 09:30
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
optimizeLogLikelihood
optimizeLogLikelihood_MODEL1
optimizeLogLikelihood_all
optimize_fixed_point
plotLamperti_V2
plotLogLikelihood
plotLogLikelihood_MODEL1
plot_epsilon
plot_theta0_gamma_model_1
testingFile
DOWNLOAD
initial_guess.m
SOURCE CODE
function [est] = initial_guess(real_prod, M, N, dt)
    % 09/02/2020 09:30
    est = 0;
    for i = 1:M
        numerator = 0; denominator = 0;
        for j = 1:N
            numerator   = numerator + (real_prod(i,j+1) - real_prod(i,j))^2;
            denominator = denominator + real_prod(i,j)*(1-real_prod(i,j));
        end
        est = est + numerator/denominator;
    end
    est = est / (2*M*dt);
end