Description of lamperti_transform
Home > . > lamperti_transform.m
lamperti_transform
PURPOSE
29/03/2020 17:49
SYNOPSIS
function [val] = lamperti_transform(theta_0,alpha,v,p,candidate)
DESCRIPTION
 29/03/2020 17:49
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
batch_with_theta_L
histogram_lamperti_SDE
moments_verification_Lamperti
path_simulator_Lamperti
testingFile
SOURCE CODE
function [val] = lamperti_transform(theta_0,alpha,v,p,candidate)
    % 29/03/2020 17:49
    if candidate == 1
        val = (1/sqrt(2*alpha*theta_0)) * asin(2*(v+p)-1);
    elseif candidate == 2
        val = -sqrt(2/(alpha*theta_0)) * asin(sqrt(1-v-p));
    end
end