Description of likelihood_nested_optimization_L
Home > . > likelihood_nested_optimization_L.m
likelihood_nested_optimization_L
PURPOSE
SYNOPSIS
function [x0,fval] = likelihood_nested_optimization_L(batch, x0, dt)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
batch_with_theta_L
likelihood_optimization_L 29/03/2020 11:20
This function is called by:
fixed_point_function
optimizeLogLikelihood
plotLamperti
DOWNLOAD
likelihood_nested_optimization_L.m
SOURCE CODE
function [x0,fval] = likelihood_nested_optimization_L(batch, x0, dt)
    disp('================================================');
    disp(['Initial values: Theta_0 = ',num2str(x0(1)),' and alpha = ',num2str(x0(2))]);
    disp('================================================');
    batch   = batch_with_theta_L(batch, x0(2), x0(1));
    fun     = @(x) -likelihood_optimization_L(batch, x(1), x(2), dt);
    [x0,fval] = fminsearch(fun, x0);
end