Description of likelihood_optimization_all
Home > . > likelihood_optimization_all.m
likelihood_optimization_all
PURPOSE
10/02/2020 11:20
SYNOPSIS
function [val] = likelihood_optimization_all(batch, theta_0, alpha, delta, dt, N)
DESCRIPTION
 10/02/2020 11:20
CROSS-REFERENCE INFORMATION
This function calls:
batch_with_theta
first_log_LH_evaluation function [value,m2,xi1,sig2] = first_log_LH_evaluation(batch_complete, theta_0, alpha, delta, dt, N, norm, times)
log_LH_evaluation
This function is called by:
optimizeLogLikelihood_all
DOWNLOAD
likelihood_optimization_all.m
SOURCE CODE
function [val] = likelihood_optimization_all(batch, theta_0, alpha, delta, dt, N)
    % 10/02/2020 11:20
    disp(['Theta = ',num2str(theta_0),', Alpha = ',num2str(alpha),', Delta = ',num2str(delta)]);
    batch_complete = batch_with_theta(batch, alpha, theta_0);
    if theta_0 < 0 || alpha < 0 || delta < 0
        val = - Inf;
    else
        val = log_LH_evaluation(batch_complete, alpha, theta_0, dt) - ...
            first_log_LH_evaluation(batch_complete, theta_0, alpha, delta, dt, N, 1e6, 1e6);
    end
end