Description of load_data_eps_test
Home > . > load_data_eps_test.m
load_data_eps_test
PURPOSE
18/03/2020 10:41
SYNOPSIS
function [Table_Testing_Complete] = load_data_eps_test(ep,dataSet,dataKind,set_type)
DESCRIPTION
 18/03/2020 10:41
CROSS-REFERENCE INFORMATION
This function calls:
load_data 19/04/2020 15:45
load_data_comparable 19/04/2020 15:45
pe
pe_dot
This function is called by:
autocorrelation_test
autocorrelation_test_Lamperti
cross_correlation_test
cross_correlation_test_Lamperti
fokker_planck_solver
histogram_M1_SDE
histogram_classic_SDE
histogram_lamperti_SDE
moments_verification
moments_verification_Lamperti
moments_verification_MODEL1
path_simulator_IG
path_simulator_Lamperti
path_simulator_OPT
path_simulator_OPT_forSuppMat Supplementary Material for the Wind-Power Paper.
path_simulator_OPT_model_1
testingFile
SOURCE CODE
function [Table_Testing_Complete] = load_data_eps_test(ep,dataSet,dataKind,set_type)
    % 18/03/2020 10:41
    if strcmp(dataKind,'classic')
        if strcmp(set_type,'testing')
            [~, Table_Testing_Complete, ~] = load_data(dataSet);
        elseif strcmp(set_type,'training')
            [Table_Testing_Complete, ~, ~] = load_data(dataSet);
        end
    elseif strcmp(dataKind,'comparable')
        [~, Table_Testing_Complete, ~] = load_data_comparable(dataSet);
    end
    Time      = Table_Testing_Complete.Time;
    Forecast  = Table_Testing_Complete.Forecast;
    Real_ADME = Table_Testing_Complete.Real_ADME;
    dt         = Time(1,2);
    [M, ~] = size(Forecast);
    for i = 1:M
        Forecast(i,:)          = pe(Forecast(i,:), ep);
        Forecast_Dot(i,:)      = pe_dot(Forecast(i,:), dt);
        Error(i,:)             = Real_ADME(i,:) - Forecast(i,:);
        Error_Transitions(i,:) = Error(i,2:end) - Error(i,1:end-1);
    end
    Table_Testing_Complete.Forecast          = Forecast;
    Table_Testing_Complete.Forecast_Dot      = Forecast_Dot;
    Table_Testing_Complete.Error             = Error;
    Table_Testing_Complete.Error_Transitions = Error_Transitions;
end