Description of log_dist_L
Home > . > log_dist_L.m
log_dist_L
PURPOSE
SYNOPSIS
function [val] = log_dist_L(z,mu,sig) % 29/03/2020 17:49
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
log_LH_evaluation_L
log_LH_evaluation_MODEL1 19/04/2020 22:09
log_LH_evaluation_MODEL1_gamma 19/04/2020 22:09
testingFile
SOURCE CODE
function [val] = log_dist_L(z,mu,sig) % 29/03/2020 17:49
    val = -(1/2)*((z-mu)/sig)^2 - log(sig*sqrt(2*pi));
end