Description of log_dist
Home > . > log_dist.m
log_dist
PURPOSE
SYNOPSIS
function [val] = log_dist(v,xi1,xi2) % 03/02/2020 11:20
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
first_log_LH_evaluation function [value,m2,xi1,sig2] = first_log_LH_evaluation(batch_complete, theta_0, alpha, delta, dt, N, norm, times)
log_LH_evaluation
plot_log_LH
DOWNLOAD
log_dist.m
SOURCE CODE
function [val] = log_dist(v,xi1,xi2) % 03/02/2020 11:20
    a   = -1;
    b   =  1;
    val = -betaln(xi1,xi2) + (xi1-1)*log((v-a)/(b-a)) + ...
        (xi2-1)*log((b-v)/(b-a));
end