Description of moment_2
Home > . > moment_2.m
moment_2
PURPOSE
SYNOPSIS
function m2 = moment_2(v,theta_0,th1,th2,p1,p2,alpha,m1,dt,n) % 02/04/2020 15:13
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
pe_dot
theta_t
This function is called by:
first_log_LH_evaluation function [value,m2,xi1,sig2] = first_log_LH_evaluation(batch_complete, theta_0, alpha, delta, dt, N, norm, times)
log_LH_evaluation
moments_verification
SOURCE CODE
function m2 = moment_2(v,theta_0,th1,th2,p1,p2,alpha,m1,dt,n) % 02/04/2020 15:13
    p      = @(i) p1 + (p2-p1) * i/n; % We interpolate p(t).
    pe_dot = (p2-p1) / dt;
    m2(1)  = v^2;
    ds     = dt/n;
    if th1 == th2 % In this case, m_1 has exact solution and theta_t = theta_0.
        theta = @(i) th2;
        m1    = @(i) v*exp(-th1*dt*(i/n));
    else
        theta  = @(i) theta_t(theta_0, alpha, p(i), pe_dot);
    end
    for i = 2:n
        m2(i) = m2(i-1) + (-2*m2(i-1)*(theta(i-1)+alpha*theta_0) + ...
            2*alpha*theta_0*m1(i-1)*(1-2*p(i-1)) + ...
            2*alpha*theta_0*p(i-1)*(1-p(i-1))) * ds;
    end
end