Description of moment_1_L
Home > . > moment_1_L.m
moment_1_L
PURPOSE
29/03/2020 16:28
SYNOPSIS
function m1 = moment_1_L(z,theta_0,alpha,p1,p2,dt,n)
DESCRIPTION
 29/03/2020 16:28
CROSS-REFERENCE INFORMATION
This function calls:
sde_Lamperti_drift_cand2
theta_t
This function is called by:
log_LH_evaluation_L
moments_verification_Lamperti
DOWNLOAD
moment_1_L.m
SOURCE CODE
function m1 = moment_1_L(z,theta_0,alpha,p1,p2,dt,n)
    % 29/03/2020 16:28
    p_dot   = (p2-p1) / dt;
    m1(1)   = z;
    p_t     = @(i) p1 + (p2-p1) * i/n;
    ds      = dt/n;
    for i = 2:n
        Theta_t = theta_t(theta_0, alpha, p_t(i), p_dot);
        m1(i)   = m1(i-1) + ds * ...
            sde_Lamperti_drift_cand2(m1(i-1),alpha,theta_0,Theta_t,p_t(i-1),p_dot);
    end
end