Description of new_batch_fixed
Home > . > new_batch_fixed.m
new_batch_fixed
PURPOSE
11/02/2020 09:35
SYNOPSIS
function [Table_Training, new_bat] = new_batch_fixed(Table_Training, batch_size, N)
DESCRIPTION
 11/02/2020 09:35
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Empitical_theta0_M1
initial_time
optimizeLogLikelihood
optimizeLogLikelihood_MODEL1
optimizeLogLikelihood_all
optimize_fixed_point
plotLamperti
plotLamperti_V2
plotLogLikelihood
plotLogLikelihood_MODEL1
plot_theta0_gamma_model_1
DOWNLOAD
new_batch_fixed.m
SOURCE CODE
function [Table_Training, new_bat] = new_batch_fixed(Table_Training, batch_size, N)
    % 11/02/2020 09:35
    Forecast     = Table_Training.Forecast;
    Forecast_Dot = Table_Training.Forecast_Dot;
    Error        = Table_Training.Error;
    new_bat      = [];
    for i = 1:batch_size
        for j = 2:N
            forecast(2*j-3:2*j-2)     = Forecast(i,j-1:j);
            forecast_dot(2*j-3:2*j-2) = Forecast_Dot(i,j-1:j);
            error(2*j-3:2*j-2)        = Error(i,j-1:j);
        end
        new_bat = [new_bat, [forecast; forecast_dot; error]];
    end
end