Description of pe
Home > . > pe.m
pe
PURPOSE
SYNOPSIS
function [pe] = pe(p, eps) % 18/03/2020 09:51
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
pe
This function is called by:
load_data_eps 19/04/2020 15:45
load_data_eps_test 18/03/2020 10:41
pe
pe_dot
theta_t
DOWNLOAD
pe.m
SOURCE CODE
function [pe] = pe(p, eps) % 18/03/2020 09:51
    for i = 1:length(p)
        if p(i) < eps
                pe(i) = eps;
            elseif p(i) >= eps && p(i) < 1-eps
                pe(i) = p(i);
            elseif p(i) >= 1-eps
                pe(i) = 1-eps;
        end
    end
end