Description of pe_dot
Home > . > pe_dot.m
pe_dot
PURPOSE
SYNOPSIS
function [pe_dot] = pe_dot(pe, dt) % 18/03/2020 10:01
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
pe
pe_dot
This function is called by:
load_data_eps 19/04/2020 15:45
load_data_eps_test 18/03/2020 10:41
moment_1 02/04/2020 15:16
moment_2
pe_dot
theta_t
DOWNLOAD
pe_dot.m
SOURCE CODE
function [pe_dot] = pe_dot(pe, dt) % 18/03/2020 10:01
    pe_dot = (pe(2:end) - pe(1:end-1)) / dt;
end