Description of sde_Lamperti_FE
Home > . > sde_Lamperti_FE.m
sde_Lamperti_FE
PURPOSE
03/04/2020 20:37
SYNOPSIS
function sim_path_f = sde_Lamperti_FE(sim_path_i,alpha,theta_0,Theta_t,dt,P,P_dot,candidate)
DESCRIPTION
 03/04/2020 20:37
CROSS-REFERENCE INFORMATION
This function calls:
sde_Lamperti_drift_cand1
sde_Lamperti_drift_cand2
This function is called by:
histogram_lamperti_SDE
moments_verification_Lamperti
path_simulator_Lamperti
DOWNLOAD
sde_Lamperti_FE.m
SOURCE CODE
function sim_path_f = sde_Lamperti_FE(sim_path_i,alpha,theta_0,Theta_t,dt,P,P_dot,candidate)
    % 03/04/2020 20:37
    if candidate == 1
        sim_path_f = sim_path_i + ...
            dt * sde_Lamperti_drift_cand1(sim_path_i,alpha,theta_0,Theta_t,P,P_dot) + ...
            sqrt(dt)*randn(1);
    elseif candidate == 2
        sim_path_f = sim_path_i + ...
            dt * sde_Lamperti_drift_cand2(sim_path_i,alpha,theta_0,Theta_t,P,P_dot) + ...
            sqrt(dt)*randn(1);
    else
        error('Choose a correct CANDIDATE.');
    end
end