Description of sde_FE_MODEL1
Home > . > sde_FE_MODEL1.m
sde_FE_MODEL1
PURPOSE
SDE for X_t in MODEL 1.
SYNOPSIS
function sim_path_f = sde_FE_MODEL1(sim_path_i,alpha,theta_0,dt,P) % 02/02/2020 18:28
DESCRIPTION
 SDE for X_t in MODEL 1.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
Empitical_theta0_M1
histogram_M1_SDE
moments_verification_MODEL1
DOWNLOAD
sde_FE_MODEL1.m
SOURCE CODE
function sim_path_f = sde_FE_MODEL1(sim_path_i,alpha,theta_0,dt,P) % 02/02/2020 18:28
    % SDE for X_t in MODEL 1.
    sim_path_f = sim_path_i -theta_0*(sim_path_i-P)*dt +...
                sqrt(dt)*sqrt(2*theta_0*alpha*sim_path_i*(1-sim_path_i))*randn(1);
end