Description of theta_t
Home > . > theta_t.m
theta_t
PURPOSE
SYNOPSIS
function [theta_t] = theta_t(theta_0, alpha, pe, pe_dot) % 13/03/2020 19:09
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
pe
pe_dot
theta_t
This function is called by:
batch_with_theta
batch_with_theta_L
first_log_LH_evaluation function [value,m2,xi1,sig2] = first_log_LH_evaluation(batch_complete, theta_0, alpha, delta, dt, N, norm, times)
fokker_planck_solver
histogram_M1_SDE
histogram_classic_SDE
histogram_lamperti_SDE
initial_theta 09/02/2020 09:58
moment_1 02/04/2020 15:16
moment_1_L 29/03/2020 16:28
moment_2
moment_2_L 29/03/2020 16:50
moments_verification
moments_verification_Lamperti
path_simulator_IG
path_simulator_Lamperti
path_simulator_OPT
path_simulator_OPT_forSuppMat Supplementary Material for the Wind-Power Paper.
path_simulator_OPT_model_1
plot_epsilon
sde_Lamperti_drift_prime_cand2
testingFile
theta_t
value_function_QMM_eps
SOURCE CODE
function [theta_t] = theta_t(theta_0, alpha, pe, pe_dot) % 13/03/2020 19:09
    theta_t = max(theta_0, (theta_0*alpha + abs(pe_dot))/(min(pe,1-pe)));
end